use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ContractError {
    PoolNotFound = 1,
    InvalidContributionAmount = 2,
    InvalidMemberLimit = 3,
    InvalidRoundDuration = 4,
    InvalidGraceDuration = 5,
    InvalidPoolStatus = 6,
    AlreadyMember = 7,
    NotMember = 8,
    PoolFull = 9,
    PoolNotFull = 10,
    CreatorOnly = 11,
    InvalidRecipientOrder = 13,
    DuplicateRecipient = 14,
    AlreadyDeposited = 17,
    RoundNotReady = 18,
    RoundAlreadyFinalized = 19,
    DeadlineNotReached = 20,
    RefundNotClaimable = 21,
    ArithmeticOverflow = 22,
    AbortNotAllowed = 23,
    RefundAlreadyClaimed = 24,
    StorageInvariantViolation = 26,
    InvalidVerifierSet = 27,
    DuplicateVerifier = 29,
    VerifierCannotBeParticipant = 30,
    VerifierPolicyMissing = 31,
    CurrentRecipientOnly = 32,
    PurchaseNotFound = 34,
    UnauthorizedVerifier = 35,
    AlreadyApproved = 36,
    InvalidSeller = 37,
    InvalidDocumentDigest = 38,
    WrongRound = 39,
    PurchaseNotApproved = 40,
    InsufficientPoolBalance = 41,
    DeadlineReached = 43,
    RoundAlreadyReady = 44,
    InvalidPurchaseDuration = 46,
    InvalidSetupDeadline = 47,
    SellerCannotBeParticipant = 48,
    TermsNotProposed = 49,
    TermsVersionMismatch = 50,
    NotApprover = 51,
    AlreadyApprovedTerms = 52,
    TermsNotFullyApproved = 53,
    SetupDeadlineReached = 54,
    SetupDeadlineNotReached = 55,
    InvalidAsset = 60,
    InvalidPurchaseAmount = 61,
    PurchaseVersionMismatch = 62,
    RoundNotFound = 63,
    /// `draw_recipient` was called on a `Fixed`-order pool.
    NotDrawPool = 64,
    /// `create_pool` was given a negative `down_payment`.
    InvalidDownPayment = 65,
}
